name: dev ci cd pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SUBMODULE_TOKEN }}
          submodules: recursive

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: [ self-hosted, dev ]
    steps:
      - name: Change permission
        run: |
          sudo chown -R ${{ secrets.NAME }}:${{ secrets.PASSWORD }} ${{ secrets.build_path }}

      - name: download build artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: ${{ secrets.build_path }}

      - name: deploy temp
        run: |
          cd ${{ secrets.deploy_path }}
          ./deploy_temp.sh

      - name: deploy default
        run: |
          cd ${{ secrets.deploy_path }}
          ./deploy_default.sh

  notify-discord:
    runs-on: ubuntu-latest
    needs: [ build, deploy ]
    if: ${{ failure() }}
    steps:
      - name: Notify Discord on Failure
        uses: Ilshidur/action-discord@v2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            Workflow failed on branch dev!
          embeds: |
            [
              {
                "title": "Workflow Failure",
                "description": "The workflow has failed on branch dev.",
                "color": 16711680,
                "fields": [
                  { "name": "Repository", "value": "${{ github.repository }}" },
                  { "name": "Commit", "value": "${{ github.sha }}" },
                  { "name": "Author", "value": "${{ github.actor }}" },
                  { "name": "Action", "value": "${{ github.action }}" },
                  { "name": "Event Name", "value": "${{ github.event_name }}" },
                  { "name": "Ref", "value": "${{ github.ref }}" },
                  { "name": "Workflow", "value": "${{ github.workflow }}" },
                  { "name": "Job", "value": "${{ github.job }}" },
                  { "name": "Duration", "value": "${{ github.run_duration }}" }
                ]
              }
            ]
