name: PR Validation Workflow

on:
  pull_request:
    branches:
      - main  # main 브랜치로의 PR에만 이 워크플로우가 트리거됩니다.

jobs:
  check-branch:
    runs-on: ubuntu-latest  # 가장 일반적인 러너를 사용합니다.

    steps:
    - name: Check base branch
      run: |
        echo "PR base branch: ${{ github.base_ref }}"
        if [[ "${{ github.base_ref }}" != "dev" ]]; then
          echo "::error ::PRs must be from the 'dev' branch only."
          exit 1
        fi
